import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Bell, Home, KanbanIcon, Settings } from "lucide-react";
import Link from "next/link";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import AppContainer from "@/components/AppContainer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <header className="flex flex-row justify-between items-center bg-white px-20 py-3 border-b-1 border-gray-200">
                    <Link href={"/"} className="text-2xl font-bold text-sky-700 font-mono">ease</Link>
                    <div className="flex flex-row items-center gap-3">
                        <button className="p-2 hover:bg-gray-200 rounded-lg cursor-pointer">
                            <Settings size={18} color="gray" />
                        </button>
                        <button className="p-2 hover:bg-gray-200 rounded-lg cursor-pointer">
                            <Bell size={18} color="gray" />
                        </button>
                        <span className="bg-gray-200 p-2 rounded-full font-bold text-gray-500 hover:bg-gray-300 text-xs cursor-pointer">NJ</span>
                    </div>
                </header>
                <AppContainer>
                    {children}
                </AppContainer>
            </body>
        </html>
    );
}